# Generated by Django 4.2.7 on 2023-11-08 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='qustion',
            new_name='question',
        ),
    ]
